Fix variable references for sample in Snakefile

diff --git a/bin/Snakefile b/bin/Snakefile
--- a/bin/Snakefile
+++ b/bin/Snakefile
@@ -224,7 +224,7 @@ rule diamond_blastp:
         dmnd=DIAMOND_DB
     output:
         outdir=directory(f"{OUTPUT_DIR}/diamond_output/{PROJECT_NR}" + "{sample}_taxonomy_prots"),
-        tax=f"{OUTPUT_DIR}/diamond_output/{PROJECT_NR}" + "{sample}_taxonomy_prots/{PROJECT_NR}{sample}_taxprot"
+        tax=f"{OUTPUT_DIR}/diamond_output/{PROJECT_NR}" + "{{sample}}_taxonomy_prots/{PROJECT_NR}{{sample}}_taxprot"
     params:
         busco_dir=lambda w: f"{OUTPUT_DIR}/busco_output/{PROJECT_NR}{w.sample}_busco"
     threads: THREADS
@@ -238,10 +238,10 @@ rule diamond_blastp:
         METAEUK_FILE="{params.busco_dir}/run_ascomycota_odb12/metaeuk_output/combined_pred_proteins.fas"
 
         if [ -f "$METAEUK_FILE" ]; then
-            PROT="{output.outdir}/{w.sample}_metaeuk.faa"
+            PROT="{output.outdir}/{wildcards.sample}_metaeuk.faa"
             cp "$METAEUK_FILE" "$PROT"
         else
-            echo "MetaEuk proteins not found for sample {w.sample}: $METAEUK_FILE" >&2
+            echo "MetaEuk proteins not found for sample {wildcards.sample}: $METAEUK_FILE" >&2
             exit 1
         fi
 
